//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Measurement struct {
	ID                        int32 `sql:"primary_key"`
	DeviceID                  int32
	CreatedAt                 time.Time
	Temperature               *float64
	Humidity                  *float64
	Pressure                  *int32
	AccelerationX             *int32
	AccelerationY             *int32
	AccelerationZ             *int32
	BatteryVoltage            *int32
	TxPower                   *int32
	MovementCounter           *int64
	MeasurementSequenceNumber *int64
	Rssi                      *int32
}
